### PR TITLE
Feature/mission footer

### PR DESCRIPTION
**Pull request by breakdancingcat**
https://waynedotedu.tpondemand.com/entity/47763
See the ticket for screenshots

### Things to consider: ###
* "Bebas Kai" is used for the H2 is only on wayne.edu. I've created a new font stack based on the fonts we use widely, Lato, Noto first then Arial, Helvetica, sans-serif after that. There will be style variation based on the fonts the site has embedded.
* The Title and actual mission are hard coded because you can't expect every site to pull in the promo group with the mission statement. 
* The background image url IS from the image in the promo group, however, unless we can find a global place to keep it.

### CODE REVIEW

**Comment by robertvrabel** [comment]
@breakdancingcat I think we should have a discussion about hot linking the background image from wayne.edu. 

My thought is we should have it be part of this package, and use gulp on our sites to copy it into the public folder and link it like that. Basically how we used to do the wordmark (which is now an inline SVG).

Another option that @chrispelzer suggests is to base64 encode the image.

**Comment by nickdenardis** [comment]
My initial thoughts:

* H2 needs to be "University Mission"
* If we're already touching the layout of each site this needs to go on, I'm thinking adding BebasKai to the head while we add this to the footer is worth the consistency between wayne.edu and each site this is visible on.
* I'm not a fan to base64 since it will add non-cachable pageweight for the same asset on every single page.
* I agree hotlinking froma promotion group is not ideal, perhaps uploading to the file manager on wayne.edu allows up to have more control without having to commit the image to this repository and allows us to change it at will in the future without touching each site. I can be pursuaded either way.

**Comment by nickdenardis** [comment]
@breakdancingcat Let us know when this is ready for re-review.

**Comment by breakdancingcat** [comment]
@nickdenardis @robertvrabel @chrispelzer @tomkrupka 
Ok! This is set, ready for re-review. Updated preview in the ticket.

**Pull request merged**
