### PR TITLE
Feature/responsive tables

### PR DESCRIPTION
**Pull request by nickdenardis**
Inspired by: http://jonathanstark.com/labs/double-zebra-responsive-tables/

Prompted by: https://basecamp.com/1730484/projects/1304-wayne-edu-redesign/messages/21395287-responsive-tables#comment_129274959

Demo: https://www.dropbox.com/s/fzk3exkq86fc8rb/responsive-tables.mov

Screenshots:

screen shot 2014-04-21 at 8 57 53 pm

screen shot 2014-04-21 at 8 58 00 pm

### CODE REVIEW

**Comment by tomkrupka** [comment]
@nickdenardis Never saw this for some reason... Did this ever get implemented?

**Comment by nickdenardis** [comment]
@tomkrupka It never got implemented, but with the changes to the styleguide I'm thinking this should either be re-investigate or made in to it's own bower package for `#content` area styles.

Thoughts @robertvrabel @chrispelzer @breakdancingcat ?

**Comment by robertvrabel** [comment]
I think it would be better for each site to implement it however it needs. Since different responsive table solutions solve different problems. So with that said, I'd leave it out of the styleguide.

**Comment by tomkrupka** [comment]
Leaving it out is fine, but the solution(s) we have at the moment don't work well on mobile in my opinion.  I would love to revisit having those solutions revisited, to solve those different problems on different sites as Rob was saying.

A lot of the main problem is that people are still using tables for non table data. (which is a different problem entirely)
I can spearhead looking up some present responsive & non-responsive solutions for real table data.
I would like to re-investigate like Nick suggested.

**Comment by robertvrabel** [comment]
Closing PR due to our discussion.

**Pull request closed without merging**
